name: cibuildwheel

on:
    push:
        branches:
            - actions_dev
            - master
    workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["windows-latest"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      # - name: Install cibuildwheel and cmake for Ubuntu
        # run: |
          # sudo apt update
          # sudo apt install cmake
          # python -m pip install cibuildwheel
        # continue-on-error: true

      - name: Install cibuildwheel for Windows
        if: matrix.os == 'windows-latest'
        run: python -m pip install cibuildwheel
        continue-on-error: true



      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        continue-on-error: true

      - name: List builded wheels
        run: ls wheelhouse