name: Python Package Build and Test

on:
  workflow_dispatch:
    
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Change this to the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel pytest build --inplace

    - name: Build the package
      run: |
        python -m build
    
    - name: Install the package
      run: |
        python -m pip install ./dist/*.whl

    - name: Run tests
      run: |
        python -m pytest

    - name: Clean up
      run: |
        rm -rf dist/

